# Use the official Nginx image
FROM nginx:stable

# Copy the Nginx configuration template
COPY ./docker/nginx/default.conf.template /etc/nginx/templates/default.conf.template

# When the container starts, substitute environment variables into the template
# and output the final config, then start Nginx.
CMD ["/bin/sh", "-c", "envsubst '$PHP_HOST,$PHP_PORT' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
